### ISSUE TITLE
Alive cannot run WPF projects on VS2013 [Workaround]

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/AliveFeedback#10]
Currently we can run WPF projects in VS2015 thanks to some MSBuild tips from the Roslyn team.

However, there are some issues when it comes to using Alive on WPF projects in Visual Studio 2013. The gory details can be found at dotnet/roslyn/issues/2779.

We have a couple workarounds in mind. First of all, all users wishing to use Alive on VS2013 must install the Visual Studio 2015 Build Tools via the following.
1. Visit: https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx
2. Click "Additional Tools"
3. Click "Microsoft Build Tools 2015 RC"
4. Download and run.

Now we have two options:
- Hopefully we can figure out proper use of `pkgdef` to provide binding redirects telling VS to use the 2015 build tools.
- Alternatively, we can automatically modify `devenv.exe.config` with the proper redirects. I'd rather not do this, but it has worked in our tests and allows Alive to function on WPF projects.

We'll close this issue when we've made a decision.

**Comment by AmadeusW** [comment]
To be able to use Alive in Visual Studio 2013, **download Microsoft Build Tools 2015**
1. Visit: https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx
2. Click "Additional Tools"
3. Click "Microsoft Build Tools 2015 RC"
4. Download and run.

To be able to use Alive **with WPF projects** in Visual Studio 2013 **update your Visual Studio configuration** to use the new tools.

We've built a program that will do it for you.
    - You can [download it as an .exe](https://github.com/CodeConnect/VS2013ConfigPatch/blob/master/VS2013ConfigPatch.exe?raw=true) from GitHub. (Requires Admin Privileges)
    - You can [browse the source and build it yourself](https://github.com/CodeConnect/VS2013ConfigPatch) on GitHub.

Let us know if you have any questions about this script!

**Comment by JoshVarty** [comment]
I'm going to close this. If we change our mind regarding this workaround, we'll re-open.
