### ISSUE TITLE
Drilldown panel will overlap others

### ISSUE THREAD

**Issue by wellwind** [CodeConnect/AliveFeedback#100]
When I drill-down one member, and drill-down another nearby before one, then panel will overlap.

Is it possible to rearrange panels when two panels conflict?

And drill-down is very good UX when use large class, but when small class, I have to click the plus icon to see members. That's addition work when debugging.

![drill-down-panels](https://cloud.githubusercontent.com/assets/8186117/13429400/0a15ba40-dffb-11e5-9363-0a4a1a801a72.png)

**Comment by AmadeusW** [comment]
The only way to bring a panel to the top is to drill down to it. 
I can see your frustration by looking at the screenshot: the drill down button is obstructed and you can't bring certain panels to the top.
I will try to fix this issue.
