### ISSUE TITLE
MsTest can't detect test cases

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#101]
version: 1.3.12
When I write some test case by MsTest and click "Autofilter", Alive didn't detect any test cases. But NUnit works.

![image](https://cloud.githubusercontent.com/assets/1528587/13490023/1ebca042-e165-11e5-8df4-20d71b840e14.png)

It should be the latest version's problem.

**Comment by JoshVarty** [comment]
Very strange, we'll look into this. If you click "Refresh" does it find them?

Also, are there any errors in the output window?

**Comment by JoshVarty** [comment]
Oh, one more question since you mentioned NUnit, are there MSTest and NUnit tests in the same project? Currently Alive is set up to look for only one test framework per project, so that might be an issue as well.

**Comment by hatelove** [comment]
@JoshVarty , you got the point. Because I use specflow and modify app.config to switch my test framework from NUnit(default setting) to MsTest. 

Although there is only one test framework in all test cases, my test project still referenced nunit.framework.

It looks like Alive will confuse when test project has already referenced NUnit but all test cases wrote by MsTest. 

So "Alive is set up to look for only one test framework per project" means Alive look for project reference, not parse test cases' attributes. Is my understanding right?

Conclusion:
When I remove nunit.framework reference, Alive works again. So the root cause should be my project referenced "Visual studio UnitTestFramework" and "nunit.framework"

**Comment by JoshVarty** [comment]
Yeah that's right. We first look for xUnit, then NUnit and then finally MSTest. Part of the reason we put MSTest last is that we noticed when you create a new "Unit Test Project" it adds the MSTest references by default and some people forget to remove them.

In theory we could support multiple test frameworks for a single project, but it would make performance slower when autofiltering and refreshing.

**Comment by hatelove** [comment]
@JoshVarty , thanks for your response. Now I know how alive look for and I'll keep it in mind and remove the other test framework reference. I totally agree it's a trade-off about performance. So I don't think this is a bug, maybe add this information on somewhere to notice user would be great.

**Comment by AmadeusW** [comment]
I've done some tests with supporting multiple frameworks per project and the performance hit is negligible for all but one test project. We will investigate this further.

**Comment by AmadeusW** [comment]
We've added support for multiple test frameworks per project in [v1.3.13](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3.13) :bee: 
Thanks for your feedback!
