### ISSUE TITLE
LINQ to SQL works but LINQ TO EF does not.

### ISSUE THREAD

**Issue by rstlaurent** [CodeConnect/AliveFeedback#102]
Are you planning to make  LINQ to EF work?

I get this : Unhandled MetadataException: Unable to load the specified metadata resource.

**Comment by rstlaurent** [comment]
I changed my connectionString to simplify the metadata section and it works now.

from this:
connectionString="metadata=res://_/DatabaseFirstModel.csdl|res://_/DatabaseFirstModel.ssdl|res://*/DatabaseFirstModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=(local)\SQLEXPRESS;initial catalog=NorthWind;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />-->
    <add name="NorthWindEntities" 

To this:
connectionString="metadata=res://*/;provider=System.Data.SqlClient;provider connection string=&quot;data source=(local)\SQLEXPRESS;initial catalog=NorthWind;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />

**Comment by rstlaurent** [comment]
I had to search a bit but I found the solution.

**Comment by AmadeusW** [comment]
@rstlaurent did your original connectionString work, but you needed to change it to use Alive?
We'd like to provide a seamless experience where you don't need to change your code, so please us know how we can improve.

**Comment by JoshVarty** [comment]
Your workaround works, but was probably only needed due to a bug I accidentally introduced when I was adding support for EntityFramework. Today I fixed that bug and it will be pushed out in our next release later this week.

**Comment by rstlaurent** [comment]
Yes, the original connnectionString worked well. I will wait for the next release for the bug fix.
Thank you for the quick reply.

**Comment by AmadeusW** [comment]
I'm sorry for the delay, and thank you for bringing this up to our attention!
We've just released a fix in [v1.4](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4) :bulb:
