### ISSUE TITLE
Mouse hover conflict with supercharger extension

### ISSUE THREAD

**Issue by totpero** [CodeConnect/AliveFeedback#107]
Hi,

If you have install [superchanger ](http://supercharger.tools/)extension and alive extension installed in vs, the `Code Flow Lines` from superchanger enter in conflict with alive mouse hover button.

**Comment by JoshVarty** [comment]
We'll take a look at this today and hopefully figure out a way that both extensions can co-exist.

**Comment by totpero** [comment]
OK, Thanks.

**Comment by AmadeusW** [comment]
We've adjusted the ordering of elements in the text editor and this won't be an issue in the next release of Alive.

**Comment by AmadeusW** [comment]
We've just released a fix in [v1.4](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4) :bulb:

**Comment by totpero** [comment]
Good, Thanks. :+1:
