### ISSUE TITLE
VS 2013 "TypeLoadException: Could not load type...". internal keyword issues?

### ISSUE THREAD

**Issue by JoanComasFdz** [CodeConnect/AliveFeedback#108]
I am facing this situation with a very simple class and its unit test:

The class:

```
internal interface IMyDependency
{
}

internal class MyClass
{
    private readonly IMyDependency dependency;

    public MyClass(IMyDependency dep)
    {
        this.dependency = dep;
    }

    public bool MyMethod(int i)
    {
        return true;
    }
}
```

The unit test:

```
[TestInitialize]
public void Setup()
{
    this.dependency = Substitute.For<IMyDependency>();
    this.testee = new MyClass(this.dependency);
}

[TestMethod]
public void MyClass_ValidParam_ReturnsTrue()
{
    var result = this.testee.MyMethod(1);

    Assert.IsTrue(result);
}
```

When I try t execute MyMethod through a unit test and select **MyClass_ValidParam_ReturnsTrue** from the test list, i get the following error:

> [Error v1.3.13-vs12.0] Unhandled TypeLoadException: Could not load type 'MyProject.IMyDependency' from assembly 'MyProject', Version=1.0.0.0, Culture=neutral, PublicKeyToken=...'.

To be able to use NSubstitute in my Unit Testing project I had to add the [InternalsVisibleTo](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute%28v=vs.110%29.aspx) attribute to MyProject AssemblyInfo.cs.

Can this error have something to do with it?

Thanks

**Comment by JoanComasFdz** [comment]
Well that is weird. The code I was trying is from a VS extension I'm developing. The extension was already installed and after some cleanups and rebuilds the error that the extension cannot be uninstalled appeared in Build output..

Uninstalled the extension, restarted and now it works.

**Comment by AmadeusW** [comment]
We also get this kind of exception when we update a certain project in Alive. This issue happens because there is a conflict between a DLL in a publicly released version of Alive installed in the main VS and a modified version of the DLL in the experimental instance of VS. 
IIRC we solve it by rebuilding (clean + build) the solution.

That's good to hear that you code works. Let us know when it doesn't!
