### ISSUE TITLE
How do I handle methods with out argument(s)?

### ISSUE THREAD

**Issue by savehansson** [CodeConnect/AliveFeedback#112]
Pretty stupid example:

``` c#
public void FakeExample(string indata, out string outdata)
{
    outdata = indata;
}
```

**Comment by AmadeusW** [comment]
We never implemented it. 
We have a plan to support this any many other atypical scenarios with a full editor, but it will take a couple weeks to build.

I'll attempt to build a workaround because Alive really needs to support this. I'll keep you updated.

**Comment by AmadeusW** [comment]
I've added support for `ref` and `out` parameters, and it will be available in the next update!

**Comment by AmadeusW** [comment]
@hawkunsh we've added support for directly invoking a method with `ref` and `out` parameters 
in [Alive 1.4.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4.2). When launching the method,
- Value for the `ref` parameter does not need to be preceded with `ref`
- Value for the `out` parameter can be anything, it doesn't matter
- Alive provides a suggestion with sample parameter values that will work

for example:
![](https://i.gyazo.com/5408417a88397ca6ea6cb8f91efb02ac.png)
