### ISSUE TITLE
Alive prevents me from clicking on the CodeLens test status icon

### ISSUE THREAD

**Issue by savehansson** [CodeConnect/AliveFeedback#114]
When Alive is enabled I can't click on CodeLens test status icon, here hovered by mouse pointer:

![image](https://cloud.githubusercontent.com/assets/650548/14488477/cd214804-0168-11e6-9166-8b9f649c6481.png)

**Comment by AmadeusW** [comment]
We fixed it in [1.4.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4.1) and I just double checked that the CodeLens icon is clickable
![](https://i.gyazo.com/c7ce74639d46e9a8f1aed4d199fda06b.gif)
Let me know if it doesn't work for you in 1.4.1 or 1.4.2

**Comment by savehansson** [comment]
It works now! Thanks!
