### ISSUE TITLE
Show line number in error tooltip?

### ISSUE THREAD

**Issue by savehansson** [CodeConnect/AliveFeedback#115]
Is it possible to also show the line number in the tooltip when hovering the error icon, like this:

![image](https://cloud.githubusercontent.com/assets/650548/14488677/a7585eea-0169-11e6-8c2f-433f17a874a8.png)

Not a big issue. One can always scroll through the code to find where Alive stops showing its output values (and the code after that line is also dimmed).

**Comment by savehansson** [comment]
Ehh.. this was a stupid question. The lines with errors are shown, but not for exceptions, and in that case the line number for the exception is the test method starting line.

**Comment by AmadeusW** [comment]
We are experimenting with using PDBs to extract line number information, so this might be possible in future versions of Alive
