### ISSUE TITLE
Fody / PostSharp

### ISSUE THREAD

**Issue by michalsteyn** [CodeConnect/AliveFeedback#118]
We use Fody a lot to implement automatic IPropertyChanged Notification.

It seems that the post build steps are not compiled when using Alive. Unfortunately running the code in Alive then completely changes the behavior. With the popularity of PostSharp, this also really limits the code that can be used in Alive.

Are you looking into supporting Fody / PostSharp?

**Comment by AmadeusW** [comment]
I'm sorry but we won't support PostSharp. A custom build task will take significant amount of time each time user interacts with the code, and ultimately fail to deliver instant feedback.
Alive will support [C#7 generators](https://github.com/dotnet/roslyn/blob/features/generators/docs/features/generators.md), though.
