### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by dfinlen** [CodeConnect/AliveFeedback#121]
Is there an easy way to modify the font size.  I've spent the last 30 minutes looking through all the documentation, but I'm not seeing anything.  Is there a file I can open and modify?

**Comment by AmadeusW** [comment]
The only way to increase the font size of Alive is by increasing the font size of the Editor. 
![zoom](https://cloud.githubusercontent.com/assets/1673956/15232888/13765888-1859-11e6-8909-91ce2369dd8a.PNG)

Is there some particular piece of text that you found too small?

**Comment by dfinlen** [comment]
When you mouse over the value, is there a way to increase that size?

**Comment by dfinlen** [comment]
![test](https://cloud.githubusercontent.com/assets/4594138/15254280/000acdd2-1904-11e6-953c-189f00929f94.png)

**Comment by dfinlen** [comment]
I don't want to detract from any gui work that is going on, since I think the output needs to be reworked and made easier to understand and read. Maybe a props panel that populated based on the line of code would be a good idea. I'm sure you have thought about this and have plans.

**Comment by AmadeusW** [comment]
We considered a window but decided against it for sake of simplicity. We may reconsider this in the future when the amount of data we show causes clutter.
For now, it will be absolutely possible to increase the font size in the tooltip. I'll look into this.

**Comment by AmadeusW** [comment]
We've addressed this in version [1.4.3](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4.3) :leaves: 
Please share any feedback!
