### ISSUE TITLE
.NET Core doesn't seem to be supported

### ISSUE THREAD

**Issue by twsouthwick** [CodeConnect/AliveFeedback#122]
I recently installed the .NET Core SDK preview tooling for VS (https://www.microsoft.com/net/core) and whenever I try to use Alive with a console app, it fails saying it cannot find `System.Object`:

![screenshot 2](https://cloud.githubusercontent.com/assets/583206/15517998/8d0d8ea0-21af-11e6-9bc3-462bb443facf.png)

**Comment by JoshVarty** [comment]
Sorry for the delay.

We've been delaying our support for .NET Core until they nail down the requirements. As you may have heard there has been a lot of volatility surrounding ProjectJson recently. Roslyn itself doesn't provide an easy way to work with these projects yet.

I'm hoping the next RC will confirm that breaking changes are behind us and we can begin to investigate properly supporting it.

**Comment by vanderstack** [comment]
I would like to add in dot net core support myself. My initial guess is that this functionality would be in the ExecutionEngine, but it may also be in the RemoteInstrumentation. tracing it from ProjectOrange to the correct calling assembly would be a lot of work, I don't suppose you could you point me in the right direction?
