### ISSUE TITLE
download from visualstudiogallery problem

### ISSUE THREAD

**Issue by wellxion** [CodeConnect/AliveFeedback#130]
Is it stop maintain?
I can't access any download page from visualstudiogallery anymore.
(And then in comealive.io seems like lot of page not found)

**Comment by JoshVarty** [comment]
Alive was [acquired by Microsoft](https://comealive.io/Code-Connect-Joins-Microsoft/) who and we're now working on it there. We won't be distributing it through the VS Gallery any more.

If you purchased a copy of Alive and would like to download our last release (which should continue working) please send an email to aliveq@microsoft.com and someone will send you the extension.
