### ISSUE TITLE
Alive won't start when Developer Assistant is enabled

### ISSUE THREAD

**Issue by MagikMan74** [CodeConnect/AliveFeedback#15]
Developer Assistant is a VS extension by Microsoft that provides quick access to code snippets.
https://visualstudiogallery.msdn.microsoft.com/a1166718-a2d9-4a48-a5fd-504ff4ad1b65

When it's enabled, I am unable to use Alive. It doesn't give any sort of error, it just doesn't come on. It's an easy enough fix for me by just disabling the extension, I forgot I even had it installed.

**Comment by AmadeusW** [comment]
Thank you. I'll investigate what happens.

**Comment by JoshVarty** [comment]
Unfortunately we haven't been able to repro this issue. If you're still facing it, feel free to let us know and we'll re-open for investigation.
