### ISSUE TITLE
Ability to control Alive by keyboard only

### ISSUE THREAD

**Issue by SharlatanY** [CodeConnect/AliveFeedback#17]
I often switch between methods when developing and e.g. when I'm working on method _A_ and realize I have to create or edit method _B_, I switch to that method and when I come back to _A_, I have to launch Alive again because it isn't active for the method anymore.

It'd  be great if I wouldn't have to use the mouse since switching between keyboard and mouse always gets you out of the flow.

Some ideas to solve this would be:
- Save that you want this method to be inspected by Alive if you're working inside of it
- Add a keyboard shortcut to toggle Alive on/off in the current method (preferably a configurable shortcut so you don't run into any problems with shortcuts from VS or other plugins)

I'm sure there are other approaches too and I don't mind much which one would be implemented (although if i _had_ to choose, I'd probably go for the keyboard shortcut) as long as I don't need to constantly switch from the keyboard to the mouse and back to activate Alive.

**Comment by JoshVarty** [comment]
Yeah this is something that's been bugging us in day-to-day usage of Alive as well.
1. Keyboard shortcuts are a must. 
2. Perhaps Alive shouldn't turn off when you stop editing the current method. If you start Alive on  `methodA()` perhaps you should be able to edit `methodB()` and `propertyC` and Alive should keep running on `methodA()`.

**Comment by AmadeusW** [comment]
Regarding 2, staying on is the best option. If it turns out to be not feasible, we can re-launch Alive as soon as we put the cursor over the target method (and keep doing it until Alive is explicitly stopped)

**Comment by SharlatanY** [comment]
@JoshVarty 2 sounds like a nice idea as well! In combination with a shortcut I imagine that it'd exactly behave like i wished it would.

**Comment by AmadeusW** [comment]
**The release is imminent** :tada: 

We've overhauled the UI and added keyboard shortcuts
![keyboard shortcut video](http://i.gyazo.com/559404887e65b8248679c0fdb253aab2.gif)

**Comment by AmadeusW** [comment]
This has been implemented in [Alive 0.5](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.5) and will be shipped today.
