### ISSUE TITLE
Activating Alive without Internet connection

### ISSUE THREAD

**Issue by thomasdon** [CodeConnect/AliveFeedback#18]
I need to be able to activate Alive on a PC without Internet access. Is this possible?

**Comment by AmadeusW** [comment]
Not at the moment, but we'll make it happen. Do you communicate with this PC through intranet? Can this PC access other file systems over the network?

**Comment by thomasdon** [comment]
No, this is a standalone PC, as are many other PCs that I program on. By the way, is the license per user or per PC?

**Comment by AmadeusW** [comment]
It's per user, for you to use on your PCs. You'll have to activate Alive on each PC.

**Comment by AmadeusW** [comment]
Fixed in 0.2.2. We will be pushing out the update tonight.

**Comment by JoshVarty** [comment]
To expand on Amadeus' point:

If you get the new version of Alive via the Extensions Manager in Visual Studio these are the steps to 
complete offline verification:
1. Open a C# solution
2. Alive will prompt you for a key. Click "Register Offline"
3. Follow the instructions to generate a Validation Request that contains your license and PC info.
4. Email that validation request to us.
5. We'll give you a Validation Confirmation file.
6. In the Alive license prompt click  "Activate" and load the Validation Confirmation file
7. Click Proceed

Let us know if you have any problems or need any assistance. Eventually we'll allow you to do this without emailing us by uploading the file to our site and then downloading the Validation Confirmation file.

**Comment by thomasdon** [comment]
OK. A question, though. I was told the licensing is per developer, and not per PC. If the Validation Request contains PC info, won't the Validation Confirmation file be specific to that PC?

**Comment by JoshVarty** [comment]
It's per-user in the sense that a user can have multiple PCs and use the license on all of them. However we do check to make sure the license hasn't been activated on too many machines. (Otherwise one leaked license key would be enough for millions of activations).

So while one user may use their license on multiple PCs, they must activate that license for each PC they install Alive on.
