### ISSUE TITLE
Launching static functions with array arguments not working

### ISSUE THREAD

**Issue by fubar-coder** [CodeConnect/AliveFeedback#19]
It seems that launching static functions with array arguments doesn't work. I get the "Launch" dialog, but when I enter the array argument and click on "Launch", nothing happens.

``` csharp
        public static void Test2(int[] args)
        {
            var c = args[0] + args[1];
        }
```

I tried to enter the arguments in the following ways:
- `1, 2`
- `new[] { 1, 2 }`
- `new int[] { 1, 2 }`
- `new int[2] { 1, 2 }`
- `{ 1, 2 }`
- `[ 1, 2 ]`

Nothing seems to work.

**Comment by JoshVarty** [comment]
Sorry, we still need to finish this functionality up. Basically we can't evaluate expressions like `new int[] {1, 2}` quite yet. But we definitely plan to support this in the near future.
