### ISSUE TITLE
Displaying incorrect result from an if statement

### ISSUE THREAD

**Issue by AmadeusW** [CodeConnect/AliveFeedback#21]
We're evaluating if statements (other statements) wrong

![ifstatements](https://cloud.githubusercontent.com/assets/1673956/8010475/74703282-0b7e-11e5-9e9d-a767d7095965.PNG)

**Comment by JoshVarty** [comment]
I think we'll show just the full unary expression for now.

**Comment by JoshVarty** [comment]
Fixed in v0.2.3
