### ISSUE TITLE
Does this tool work with standard debug sessions?

### ISSUE THREAD

**Issue by aarondandy** [CodeConnect/AliveFeedback#27]
Note: Sorry if these things already work, but I have no way of knowing.

I see in the videos that this tool works by running tests. Can this tool also work with a standard debugging session, remote debugging even?

**Comment by AmadeusW** [comment]
Alive works independently of the debugging session. It runs the code **locally**, as you write it. 

You can use Alive during the debugging session, allowing you to peek at the code execution from the test's point of view, at the same time as your code is executed by either local or remote debugger.

![screenshot showing Alive running together with the debugging session](http://i.gyazo.com/f73fe484db85cd26cc4224ee8935152d.png)

Does it answer your question? Let me know if you have any other questions.

**Comment by aarondandy** [comment]
To use a scenario, pretend I have an application behaving incorrectly in our Dev environment. I would like to attach the VS debugger to that process and see what is going on. Will Alive work then, or only during test execution that it controls?

**Comment by JoshVarty** [comment]
Alive works during design time, when you're writing new code or editing existing code. The idea behind Alive is that when you're reading and writing code, it's really helpful to see the data your code will manipulate. We provide this data by running one of your tests.

So Alive isn't intended to work when you've attached a debugger to a running process.

**Comment by JoshVarty** [comment]
I'm going to close this now, if you have any further questions feel free to re-open or to start another issue. :)
