### ISSUE TITLE
Discover tests for methods that reference current method

### ISSUE THREAD

**Issue by jonstelly** [CodeConnect/AliveFeedback#28]
From just briefly working with Alive in a solution where we focus a bit more on integration tests than unit tests, it would be nice if:

When looking at a method in Visual Studio, Alive not only found tests that directly invoked that method, but maybe go up 1 level and find all tests that invoke a method that invokes this method.  Like ReSharper's find references, just step up 1 level and show me all matching tests.

**Comment by AmadeusW** [comment]
Thank you for the suggestion.

We are investigating various holistic uses of Alive, and what you suggested is possible with data that we gather. I would like to ask you more questions to understand your needs are and what kind of user interface would be best.

What would you like to do with tests that invoke the parent method? Would you like to run them and see their effect on the parent method?
Would you like to navigate to the test, to the parent method, or another method on the call stack?

At Code Connect we've built another Visual Studio extension that your may find useful - [Code Connect](http://codeconnect.io/). It allows you to see and navigate through the code in your solution on a call-stack basis. _Currently it doesn't work in Visual Studio 2015 but we are working on getting it fixed ASAP._

**Comment by JoshVarty** [comment]
If I'm understanding you correctly you're saying that if we have the following code:

``` CSharp
[TestMethod]
public void TestMethod()
{
    MethodA();
}

public void MethodA()
{
    MethodB();
}

public void MethodB()
{
    int x = 5;
}
```

Are you saying for the above code, we should be able to run `TestMethod` and work within `MethodB`? That behavior is actually already supported in Alive. If you're not seeing this, please let us know.

(Alive maps tests to every method invoked directly or indirectly by the test)

**Comment by jonstelly** [comment]
That example looks right.  The more detailed real-world situation I have is that MethodA would be in a Service class which calls into MethodB that lives in a Repository class.  When I use the Alive button next to the MethodB method, it says there are no tests that invoke my method.

I know some of the tests we have are [NUnit Parameterized Tests](http://nunit.org/index.php?p=parameterizedTests&r=2.5), and I know those aren't getting picked up (understandable, those are sort of odd birds).  But I'll extract a concrete sample solution to verify the behavior and update this issue with my findings.

**Comment by JoshVarty** [comment]
It sounds to me like it's a bug on our end. When you click "Discover" tests, can you take a look at the output window and see if there are any exceptions or errors being reported?

![image](https://cloud.githubusercontent.com/assets/1249087/8861515/cf4d4398-3158-11e5-8cad-7cff4b36c2d7.png)

To see Alive's output, go to `Debug` > `Windows` > `Output` and then select Alive from the Show output from drop-down.

I'll also look into the NUnit Parameterized Tests. Our goal is to support NUnit, XUnit and MSTest completely, but we still have a ways to go.

**Comment by jonstelly** [comment]
Looked into it, and the only tests we had covering the method I was expecting to see tests for were NUnit parameterized tests.  I'm going to close this issue and open an enhancement request for you guys to support NUnit Parameterized Tests.

Thanks for the prompt replies.
