### ISSUE TITLE
Support NUnit Parameterized Tests

### ISSUE THREAD

**Issue by jonstelly** [CodeConnect/AliveFeedback#29]
[NUnit Parameterized Tests](http://nunit.org/index.php?p=parameterizedTests&r=2.5) don't get discovered.

The attached test would essentially call CallGetByIdAsTestCase() twice, once with an id of 1 and another time with a value of 2.  It's also possible to use the ValueSourceAttribute attribute to point to a method that returns a collection of parameters.

It would be nice if Alive could show each test case in the discovery dialog.  Normally I imagine people would want to invoke a single run of the test case with a specific parameter.  I think ReSharper's NUnit test runner is a fairly good example of how to invoke those test cases.

```
[TestFixture]
public class SomeServiceTests
{
    [Test]
    public void CallGetByIdDirectly()
    {
        //DISCOVERED
        var service = new SomeService();
        var value = service.GetById(1);
        Assert.AreEqual("1", value);
    }

    [Test]
    public void CallGetByIdWithFakeIoC()
    {
        //DISCOVERED
        var serviceType = typeof (ISomeService).Assembly.GetTypes().SingleOrDefault(t => typeof (ISomeService).IsAssignableFrom(t) && !t.IsAbstract);

        var service = (ISomeService)Activator.CreateInstance(serviceType);
        var value = service.GetById(1);
        Assert.AreEqual("1", value);
    }

    [TestCase(1)]
    [TestCase(2)]
    public void CallGetByIdAsTestCase(int id)
    {
        //NOT DISCOVERED
        var service = new SomeService();
        var value = service.GetById(id);
        Assert.AreEqual(id.ToString(), value);
    }
}
```

**Comment by JoshVarty** [comment]
Thanks for the report @jonstelly, we've begun investigating this issue and we'll keep you updated.

**Comment by AmadeusW** [comment]
Alive will support NUnit parameterized tests in the next update which is due on August 26th :)

**Comment by jonstelly** [comment]
The latest build I see of the extension in the gallery is from 8/19.  Just making sure, I'm guessing the 8/26 release is delayed a bit?

**Comment by JoshVarty** [comment]
Yeah we had an [intermediate (v0.5.4) build](https://github.com/CodeConnect/AliveFeedback/issues/36#issuecomment-135287871) released last Wednesday, but it would have caused regressions for most users.

We've been redesigning our test runners for NUnit/xUnit/MSTest and it's taken us longer than we had anticipated. The good news is that all our tests are passing today, so I'm hopeful we can get this out by tomorrow.

Really sorry for the delay!

**Comment by jonstelly** [comment]
No problem at all, I know how that goes.  Just wanted to test this out when it's ready.  Thanks.

**Comment by AmadeusW** [comment]
In version [0.6](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6) we introduced correct functionality for invoking paramterized test cases, and in [0.6.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.2) we've refined it and introduced new UI
