### ISSUE TITLE
C# 6 support

### ISSUE THREAD

**Issue by BenjaminNitschke** [CodeConnect/AliveFeedback#30]
I am having problems getting Alive to work in my solutions using C# 6 expressions, especially when using expression bodies on methods.

For example this method works:

``` Csharp
public static string MaxStringLength(string input, int maxLength)
{
  return input.Length <= maxLength ? input : input.Substring(0, maxLength);
}
```

but once it uses the C# 6 syntax Alive just crashes:

``` Csharp
public static string MaxStringLength(string input, int maxLength)
    => input.Length <= maxLength ? input : input.Substring(0, maxLength);
```

```
[Error, Pipeline] There was an error running MaxStringLength. Stopping Alive. 
[Error, Pipeline]  -> Exception has been thrown by the target of an invocation. 
```

After that even if I revert to the old code Alive is gone and the only way to get it back is to restart VS or reload the project.

In my solution (C# 6) I unloaded everything except one base project, but trying to discover any test causes errors (Alive won't crash, but no tests will ever be found):

```
[Error, TestDiscovery] There were errors building project ... 
[Error, TestDiscovery]  -> Compilation errors in project ...
[Error, TestDiscovery] CS0162 at SampleTestClass.cs line 19 (character 1): Unreachable code detected
CS0162 at SampleTestClass.cs line 24 (character 1): Unreachable code detected
```

Some static methods even crash when no C# 6 code is involved:

``` CSharp
public static float TryParse(this string text, float defaultValue)
{
    float result;
    return float.TryParse(text, NumberStyles.Number, NumberFormatInfo.InvariantInfo, out result)
        ? result : defaultValue;
}
```

```
[Error, Pipeline] There was an error running __aliveIntermediate. Stopping Alive. 
[Error, Pipeline]  -> Alive was unable to access evaluation results. 
```

All code compiles just fine in VS2015, I can test with NCrunch, ReSharper, etc. just fine, just Alive won't eat it. Thanks for helping!

**Comment by AmadeusW** [comment]
Thank you for this comprehensive breakdown of scenarios that don't work! We will support cases that you've mentioned.
Alive should gracefully recover from any problems, so this is a bug on our end that we will fix.

**Comment by JoshVarty** [comment]
Thanks for the detailed report @BenjaminNitschke. It definitely makes it a lot easier to figure these things out.

I've assigned this issues to myself and I'm going to start investigating it now.

**Comment by BenjaminNitschke** [comment]
Thanks. Let me know if you need help testing these or if you need some sample code/solutions for reproducing these issues.

**Comment by JoshVarty** [comment]
I can't seem to reproduce this unfortunately. I created a sample solution that used the C# 6 features you mentioned, but it seems to work for me.

If you could give me a sample solution/code that'd be great. 

Another theory I had just now while reading, do you have warnings set as errors in Visual Studio? I noticed in your log:

```
 CS0162 at SampleTestClass.cs line 19 (character 1): Unreachable code detected
```

Alive rewrites your code (in a transient solution) so we may be generating code that has warnings. If this is the case, we might not be able to compile with your settings. (We could fix this by suppressing `CS0162` when we rewrite)

**Comment by BenjaminNitschke** [comment]
Thanks for investigating. You are right that I can get rid of the Unreachable code detected error by just adding #pragma warning disable 162 or disabling warnings as errors in my project (Alive should do this  for me behind the covers IMO, I opened a new issue for this), and as long as the method does not use an expression body, it works (and now it is quite cool to play around with Alive, great product).

But I still cannot get simple C#6 code to find the test for it. Here is a very simple test project with one line of C#6, that still cannot find any test calling C#6 code: http://blog.deltaengine.net/TestingAlive.zip
Reverting it to a normal method allows to Alive to find the test for it (and the simple Abc method below it works fine too).

I also still see some errors from time to time from Alive (bigger project than the attached one, I could try to replicate it in the small attached project if you need it):

```
[Error] An exception wasn't caught until the API boundary: Object reference not set to an instance of an object. 
[Error]  -> Object reference not set to an instance of an object. 
[Message] After unloading a project, you must re-discover test case mapping. 
```

```
[Error, TestDiscovery] Error running test case GetBinaryOperatorMethodName 
[Error, TestDiscovery]  -> Parameter count mismatch. 
[Error, TestDiscovery] Error running test case GetBinaryOperatorSymbol 
[Error, TestDiscovery]  -> Parameter count mismatch. 
[Performance, TestDiscovery, Message] 2015-07-27 10:07:43Z - Test case invocation - 128 ms. 
[TestDiscovery, Message] Alive finished test discovery. 
```

For example the GetBinaryOperatorMethodName looks like this:

``` csharp
        [TestCase(BinaryOperator.Add)]
        [TestCase(BinaryOperator.Subtract)]
        public void GetBinaryOperatorMethodName(BinaryOperator binaryOperator)
        {
            Assert.That(Base.Number.GetBinaryMethod(binaryOperator).Name,
                Is.EqualTo(binaryOperator.ToString().ToLower()));
        }
```

**Comment by JoshVarty** [comment]
Internally I've added support for using Alive on expression bodied methods. (Both when they're static and when they're hit by a unit test). I'll update you once we've got this fix in a release. 

We're hoping to get a release out with this fix and some others later this week.

**Comment by AmadeusW** [comment]
@BenjaminNitschke expression bodied methods can be evaluated in [v0.5.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.5.1) that we've just released.

**Comment by JoshVarty** [comment]
Our first fix rewrote void expression bodied methods incorrectly. (I didn't know there could be void expression bodied methods).

Our 0.5.2 release has corrected this mistake.
