### ISSUE TITLE
Suppress warnings generated by alive or compile without Warnings as Errors

### ISSUE THREAD

**Issue by BenjaminNitschke** [CodeConnect/AliveFeedback#31]
As mentioned in issue #30 when using the Warning as Errors setting in a C# project, alive might produce code that produces warning 162 (unreachable code) and causes compiler errors (even though the original code works just fine). Alive should either suppress these warnings via #pragma warning disable 162 or just not using the Warning as Errors compiler switch.

**Comment by AmadeusW** [comment]
Thank you for catching this.
I've assigned this issue to myself and I will fix it for the next update.

**Comment by JoshVarty** [comment]
This is fixed internally and will be published shortly in our next release.

**Comment by AmadeusW** [comment]
Fixed in [v0.5.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.5.1)
