### ISSUE TITLE
How do I see if a test failed?

### ISSUE THREAD

**Issue by horsdal** [CodeConnect/AliveFeedback#32]
I'm running Alive on https://github.com/horsdal/nancy.linker where I have few xUnit tests. They are discovered just fine and can be launched just. But when I break the code, rebuild and relaunch all tests I can't see if Alive is telling that the tests failed.
I'm running v. 0.5.

**Comment by JoshVarty** [comment]
Currently we don't show any information about whether or not the test is failing. 

However, we can detect `AssertFailedExceptions` so I think we can convey that information somehow. Perhaps indicating this via the icon might work.

**Comment by horsdal** [comment]
Yeah, I was looking at the icon and half expecting it to turn red or become and exclamation mark or something like that.

**Comment by AmadeusW** [comment]
In version [0.6.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.2) we've added a notification icon that pops up when there is an unhandled exception or a test case failing.
![notification](https://cloud.githubusercontent.com/assets/1673956/10084142/b430052a-62b6-11e5-9db2-d30aa124c4fc.png)

**Comment by horsdal** [comment]
Thanks. I'll give a try.
