### ISSUE TITLE
Directly invoke a test without having to discover all tests

### ISSUE THREAD

**Issue by brunomlopes** [CodeConnect/AliveFeedback#33]
Imagine that I have the following code:

``` c#
        [Fact]
        public void CanRenderCycle()
        {
            var templateText = @"
{% if user.payments == empty %}
   you never paid !
{% endif %}

{% if user.payments.size > 0  %}
   you paid !
{% endif %}
";
            Assert.Equal("you never paid !", RenderTextTemplate(templateText, new { user = new { payments = new List<object>() } }).Trim());
        }
```

Currently Alive needs to discover all tests to run this one, but it would be _very_ useful to just launch this one directly without having to go through the discovery phase.

**Comment by AmadeusW** [comment]
Thank you for the suggestion! There is indeed no need to discover the tests to invoke a test method.
It's on our personal wish list, too. We will let you know when it's implemented.

**Comment by AmadeusW** [comment]
We've made it possible to invoke test cases without performing the costly test discovery in [0.5.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.5.2). Now, all test cases are available to execute, and test **discovery** is now called **Autofilter**.

In the next update we will provide a shorthand to invoke a test case directly, without needing to pick it from the list. I will close this issue then.

**Comment by AmadeusW** [comment]
In version [0.6](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6) we've introduced functionality for launching test cases directly, and in [0.6.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.2) we've refined it and introduced new UI
