### ISSUE TITLE
Display Values For Instances

### ISSUE THREAD

**Issue by superspit** [CodeConnect/AliveFeedback#35]
Hi,

is it possible to display the values of instances? similar to how the test results are displayed. Even better, how visual studio does it? 

cheers

Johnny

**Comment by JoshVarty** [comment]
What sort of values would you like to see? Can you take a screen shot of what you're seeing in Visual Studio that you'd like us to emulate?

**Comment by superspit** [comment]
![aliveinstanceinspection](https://cloud.githubusercontent.com/assets/2297952/9150683/aafa9bc0-3dde-11e5-808b-7648b78dfe12.png)

does this make sense?

cheers

Johnny

**Comment by JoshVarty** [comment]
This makes a lot of sense. Very often I wish to drill down into the properties of an object as well. There are still some big engineering challenges ahead of us if we were to implement this feature, but I don't believe they're insurmountable. 

We've been talking about this internally and I'll keep you posted if we think we can make progress on this.

**Comment by JoshVarty** [comment]
We've recently implemented first level drill down in Alive.  So now you can click the + icon and expand to see the properties.

![image](https://i.gyazo.com/3f8bb59e8a71d45f67cebdff6d94cd74.gif)
