### ISSUE TITLE
Test cases are not discovered when marked with an attribute that inherits from Test

### ISSUE THREAD

**Issue by Wolfwyrd** [CodeConnect/AliveFeedback#36]
We have an internal test framework that is based on NUnit which has attributes defined to give a more BDD feel to our testing (take a look at [LeapingGorilla.Testing](https://bitbucket.org/LeapingGorillaLTD/leapinggorilla.testing)). The problem is that Alive doesn't recognise methods marked with these attributes as being runnable tests at all. Our attribute is simple:

``` c#
/// <summary>
/// Marks a method as being an assertion about the outcome of a test.
/// </summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public sealed class ThenAttribute : TestAttribute
{
}
```

Sadly because of this it means Alive provides nothing to us for development. Is this something that can be solved with an equivalent of an AssignableTo check?

Changing from `[Then]` to `[Test]` works as expected but is not something we really want to do across X thousand tests.

**Comment by JoshVarty** [comment]
Hmm. We should be able to support this.

Is there any expected behavior change between `ThenAttribute` and `TestAttribute`?

**Comment by JoshVarty** [comment]
It looks like the `Given` attribute might be the only one that changes behavior between NUnit?

https://bitbucket.org/LeapingGorillaLTD/leapinggorilla.testing/src/533c9332ee2c04f91ad9e88cdc206bd20be9c4e5/LeapingGorilla.Testing/Attributes/GivenAttribute.cs?at=default

**Comment by Wolfwyrd** [comment]
No changes in behaviour at all - it's just to fit better with Given/When/Then (rather than having Given/When/Test). For what it's worth NUnit discovers and runs them with no issue. 

The `When` and `Given` attributes are used only by the framework and don't inherit or hide anything from NUnit.

**Comment by JoshVarty** [comment]
Alright, if there's no expected changes in behavior and the NUnit test runner handles them fine then we should be able to support them by our next weekly release. (August 26)

**Comment by JoshVarty** [comment]
So I'm looking into implementing this and maybe you can help me get a little more familiar with the framework. They give the following example:

``` CSharp
public class WhenTestingStubbing : WhenTestingTheBehaviourOf
{
  [ItemUnderTest]
  public ClassRaisingAnEvent ClassRaisingEvent { get; set; }

  [Dependency]
  public IMockEventRaiser EventRaiser { get; set; }

  private string _severeResponse;
  private string _nonSevereResponse;

  private string _severeReturn;
  private string _nonSevereReturn;

  [Given]
  protected void TheEventRaiserShouldHaveDifferentReturnsBasedOnTheEventSeverity()
  {
    _severeResponse = "This is a severe response";
    _nonSevereResponse = "This is a non-severe response";

    EventRaiser.RaiseEvent(true).Returns(_severeResponse);
    EventRaiser.RaiseEvent(false).Returns(_nonSevereResponse);
  }

  [When]
  protected void TheEventRaiserRaisesASevereAndNonSevereEvent()
  {
    _severeReturn = ClassRaisingEvent.DoSomethingWithTheEventRaiser(true);
    _nonSevereReturn = ClassRaisingEvent.DoSomethingWithTheEventRaiser(false);
  }

  [Then]
  public void SevereReturnShouldMatchResponse()
  {
    Assert.That(_severeReturn, Is.EqualTo(_severeResponse));
  }

  [Then]
  public void NonSevereReturnShouldMatchResponse()
  {
    Assert.That(_nonSevereReturn, Is.EqualTo(_nonSevereResponse));
  }

  [Then]
  public void EventRaiserShouldBeCalledTwice()
  {
    EventRaiser.Received(2).RaiseEvent(Arg.Any<bool>());
  }
}
```

In this example it looks like there are a number of behavior changes when compared to NUnit. When you run the `[Then]` tests, they depend on the `[Given]` and `[When]` methods being run first, correct? 

You mentioned that changing `[Then]` to `[Test]` causes everything to work? Are you sure we can we run all your `[Then]` tests without having first run the `[Given]` and `[When]` setup methods? Does the NUnit test runner know to run these methods first?

**Comment by JoshVarty** [comment]
Upon further review it looks like the base class `WhenTestingTheBehaviourOf` takes care of running the `[Given]` and `[When]` methods. This shouldn't be too hard to support.

**Comment by JoshVarty** [comment]
Looks like I've got it going. I'll be doing some more testing, but it looks like this should be on track to be released Wednesday.

![image](https://i.gyazo.com/15c1cefc309c688f954dfb0d88402cc5.gif)

**Comment by Wolfwyrd** [comment]
That's fantastic! You're correct in your assumption - the other attributes don't alter NUnit's behaviour they just drive setup for the framework. 

Looking forward to getting my hands on the update!

**Comment by JoshVarty** [comment]
Hey @Wolfwyrd we're currently reworking our test runner. It's proven hard to fully support three test frameworks and testing shows our current release caused some regressions in xUnit support. For that reason we didn't release an updated version of Alive today.

However, we've prepared a private release of Alive that you can use and should fix your issues since you don't depend on xUnit. You can get it from: https://codeconnectcdn.blob.core.windows.net/cdn/PrivateAliveReleases/Alive.0.5.4.vsix

The release notes are available at: https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.5.4

I'm going to leave this issue open until we've got everything working 100% with our new test runner.

**Comment by JoshVarty** [comment]
So we've fixed this for LeapingGorilla but for the general case we're temporarily blocked by: dotnet/roslyn/issues/4900.

We'll investigate an approach using reflection but I'll reach out to the Roslyn team to see if there's an API that can make this easier/cleaner.

**Comment by JoshVarty** [comment]
Just cleaning up issues. We've actually added support for this quite some time ago.
