### ISSUE TITLE
Support for Specflow

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#38]
Is there any possibility to support Specflow (http://www.specflow.org/)? 

Specflow would generate unit test code from feature files, and combine with function of step definitions. It is most popular BDD and TDD solution from Cucumber. 

Using Alive to made TDD smoothly is the key reason I buy Alive license, so please consider to add specflow support to Alive, thanks.

I think it should support without trouble, because of all testing code have generated in the test project. It just could find the test cases in the test discovered window.

**Comment by hatelove** [comment]
Test exploered window can discover test cases from specflow.
Here is a example:
![test explorer window discovered](https://cloud.githubusercontent.com/assets/1528587/9754394/598f9070-56fb-11e5-8c5c-03cf47c6c933.jpg)

but I can't find all test cases in my production code function. There is only 1 test case that is coding by pure MsTest.
![wont support specflow](https://cloud.githubusercontent.com/assets/1528587/9754432/c93f1256-56fb-11e5-999e-49a301645bbd.jpg)

**Comment by AmadeusW** [comment]
Thank you @hatelove, we'll definitely look into it. Both Alive and SpecFlow aim to make unit testing better, and they would be a good fit together.

**Comment by hatelove** [comment]
This issue looks like issue 36 "Test cases are not discovered when marked with an attribute that inherits from Test ": https://github.com/CodeConnect/AliveFeedback/issues/36

**Comment by hatelove** [comment]
version 0.6.5.1, Specflow+MsTest with Alive works fine!

**Comment by AmadeusW** [comment]
:+1: I'm glad it works well! Enjoy!
