### ISSUE TITLE
Please add feature: show test case name with tip when hover the play icon

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#39]
I think it would be great when I hover the play icon and I could see the test case name on the tip. It helped us to see every status and value tally with our expectation of the test case scenario.

![tip for test case](https://cloud.githubusercontent.com/assets/1528587/9979711/3d206784-5fac-11e5-9854-b27b1d9ca9a3.jpg)

**Comment by AmadeusW** [comment]
Thank you for the suggestion @hatelove.
Coincidentally, I'm currently working on improving the launch icon as part of #32 and your suggestion will be implemented. Stay tuned for updates!

**Comment by hatelove** [comment]
Thanks, @AmadeusW! I can't wait to use the updated version! 

In addition, I have some problems about launch icon. When some error happend, it shows "X" icon.(It usually happened on compiled error.)  But no matter how I try to fix the problems, it still "X". I can't easily reload or restart the status of test case. The only way is restart Visual Studio to force Alive reload status.  It really bothered me when I live demo and promote this amazing tool. Should I open another issue for this feature (easily reload/restart status of test case)?

**Comment by AmadeusW** [comment]
I'm sorry about the issues during the demo. 
You can currently learn more about the issue that you have by examining the **Output window** (View -> Output   Ctrl+W, O). Choose **Alive** from "Show output from" dropdown. You can then forward this information to us, and we would be happy to help.
![screenshot](https://i.gyazo.com/0c93edcf784fb966846fc85d6060924f.png)

**Comment by hatelove** [comment]
Thanks @AmadeusW . I find VS2015 is more stable than VS2013. When I use VS2015 to demo my project, it works so smoothly. :+1: 
If I used VS2013 and got the problems, I will forward information from Output window for you. But I think I will migrate to VS2015 now. :laughing:

**Comment by AmadeusW** [comment]
That's great that you've found a solution that works for you! We would still appreciate a bug report for VS 2013 so that we can address this issue for our VS 2013 users :)

**Comment by AmadeusW** [comment]
Since version [0.6.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.2), when there is an unhandled exception, or a test case fails, we're displaying a notification with test case name and exception's message
