### ISSUE TITLE
[Error, Pipeline]Unable to clear scratch space.  

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#40]
When I got the below error information :

---

[Error, Pipeline] Unable to clear scratch space. 
[Error, Pipeline]  -> Access to the path 'Data.Core.dll' is denied. 
[Error, Pipeline] System.UnauthorizedAccessException: Access to the path 'Data.Core.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CodeConnect.ExecutionEngine.AssemblyHelper.ClearTempDirectory()
   at CodeConnect.ProjectOrange.Pipeline.Initialize(Workspace workspace, IVsFileChangeEx fileChangeService) 

---

I couldn't discover my test cases in Alive window.

![unable to clear scratch space](https://cloud.githubusercontent.com/assets/1528587/10001720/be6d9576-60d5-11e5-9daf-d3d0442a9278.jpg)

I launch my VS2015 and VS2013 by admin, it was still not working. In my test project, there were not "Data.Core.dll". (It should be in my other solution and projects)

**Comment by JoshVarty** [comment]
Thanks for the report and the screenshot, this should make it easier to fix.

**Comment by hatelove** [comment]
I find a [reference](http://stackoverflow.com/questions/29560011/vs2015-ctp6-does-not-discover-unit-tests-resharper-does-discover-some-of-them) from stackoverflow and try to clean my temp folders. And I reopen my project, there were no Unable to clear scratch space message, but it still couldn't discover my test cases.

My Alive version: 0.6.1
Enterprise VS2015 and Ultimate VS2013

**Comment by AmadeusW** [comment]
Unable to clear scratch space error was fixed in version [0.6.2](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.2)
