### ISSUE TITLE
Show highlight of code trace

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#44]
I wish Alive has a feature about showing the code trace in line number like break point.
![feature of code trace](https://cloud.githubusercontent.com/assets/1528587/10159406/a4c1e820-66ca-11e5-84dc-b5b5c284704a.jpg)

When we TDD, we focus on the right trace of current test case/scenario. It will help us to find the key condition or where we need add a condition in our production of current  scenario.

**Comment by JoshVarty** [comment]
We'll probably not show code trace exactly like that, but we're experimenting with some approaches to help convey what code is executing. Perhaps something like this:

![image](https://cloud.githubusercontent.com/assets/1249087/10167507/d29c3608-6696-11e5-8e4c-370d2d32d154.png)

Or maybe: 

![image](https://cloud.githubusercontent.com/assets/1249087/10167532/e7f27080-6696-11e5-89f4-e8c74e5a2405.png)

**Comment by hatelove** [comment]
Both two were awesome!  It was very clear and like some OzCode style.

**Comment by JoshVarty** [comment]
This week I'll be working on this and we hope to have it in our next release.

We've got the basics running and now we just have to extend it to a variety of language features.

![image](https://gyazo.com/d3ef6c722c259b91b3c590defdce59a8.gif)

**Comment by AmadeusW** [comment]
Thank you for the suggestion! We've just released it in [v1.4](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4) :bulb:
