### ISSUE TITLE
variable align to the right will be cut off

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#45]
![image](https://cloud.githubusercontent.com/assets/1528587/10410059/52856180-6f68-11e5-97d8-dba0e069e0b5.png)

When my code is too long, the showing variable values will be cut off. I have already hidden my right side windows or move my horizontal scroll bar, I still can't see the full status and values.

After v.0.6.3, this problem happened.

**Comment by JoshVarty** [comment]
When you scroll to the right, are you able to see the full results?

**Comment by hatelove** [comment]
No, I only see the half result. The screenshot is showing about scrolling to the right.

**Comment by hatelove** [comment]
You can adjust larger font size or view percentage to 150%, and re-launch the test case. It should also show the same problem.

**Comment by JoshVarty** [comment]
Thanks, I'll try to reproduce tomorrow and if all goes well we should hopefully have this as a fix for Wednesday.

**Comment by hatelove** [comment]
![algin to the right](https://cloud.githubusercontent.com/assets/1528587/10414658/8adf25a2-7012-11e5-958c-75ca1ebee912.gif)

attatch screenshot by gif

**Comment by JoshVarty** [comment]
Thanks, I can reproduce locally and will try to fix this quickly.

**Comment by JoshVarty** [comment]
A temporary workaround in the meantime is to scroll the mouse up or down once you've scrolled to the right:

![image](https://i.gyazo.com/bd1d672239873bafd64605e5c596032c.gif)

**Comment by hatelove** [comment]
@JoshVarty , thanks! This workaround works and easily to use.

**Comment by JoshVarty** [comment]
I've submitted a PR with a fix, so this should make it into our Wednesday release. Thanks for your help :)

![image](https://i.gyazo.com/404208be0bbe287c6cb1c524da291259.gif)
