### ISSUE TITLE
Can't find test cases until re-typing [TestClass]

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#46]
Sometimes I can't filter all test cases in the Alive Filter window. When I delete and re-type [TestClass] attribute, it works again.

Here is my operation video: https://www.youtube.com/watch?v=DnbXldg581E

VS2015, Alive v.0.6.4, using MsTest

**Comment by JoshVarty** [comment]
Thanks for the video. I've been able to reproduce this locally. It looks like `[TestClass()]` doesn't allow tests to be discovered but `[TestClass]` does. I'm not sure why, but I'll investigate this and I think we can probably get a fix into today's release.

**Comment by hatelove** [comment]
@JoshVarty , thanks for your quickly response and find the cause. It remind me something! 

I try to open my specflow test project and modify the test class and test method generated by specflow, and it works! It means if alive fix this strange bug, maybe it fix the feature request of supporting specflow: https://github.com/CodeConnect/AliveFeedback/issues/38 (because of MsTest's TestClass() and TestMethod() attribute)

**Comment by hatelove** [comment]
Good news! In fact, Alive support Specflow because specflow generate testing code when saving feature file. I try to use Specflow+NUnit and write some sample code, alive just work fine!

So there was only problem of specflow + MsTest, and this issue is the root cause.

sample feature file:
![sample feature](https://cloud.githubusercontent.com/assets/1528587/10490664/d808e72c-72d4-11e5-8b7a-9ac5e8b7c6ef.jpg)

find tet cases successfully:
![find test case](https://cloud.githubusercontent.com/assets/1528587/10490669/dcb7c7ca-72d4-11e5-9f4c-085913d9cbac.jpg)

launch normally:
![work fine](https://cloud.githubusercontent.com/assets/1528587/10490671/dfb552b2-72d4-11e5-9bff-937886d0fb3c.jpg)

show the correct failed information:
![failed info](https://cloud.githubusercontent.com/assets/1528587/10490675/e31141e6-72d4-11e5-8971-f36f97cee792.jpg)

**Comment by JoshVarty** [comment]
Glad to hear it. :) 

We'll do some internal testing before we close #38

**Comment by hatelove** [comment]
hi @JoshVarty , Now [TestClass()] works fine. But I found another problem that when it use full namespace, like "[Microsoft.VisualStudio.TestTools.UnitTesting.TestClass()]", there is the same problem.

The MsTest testing code generated by SpecFlow is "[Microsoft.VisualStudio.TestTools.UnitTesting.TestClass()]", so version 0.6.5 still doesn't discover test cases of SpecFlow + MsTest.

![image](https://cloud.githubusercontent.com/assets/1528587/10504405/b1711342-7332-11e5-991e-3fe203ec032f.png)

**Comment by JoshVarty** [comment]
:disappointed: 

My mistake, I should have created more comprehensive tests. I'll fix this and we'll release an update tonight or tomorrow. Sorry about this.

**Comment by hatelove** [comment]
That's okay, never mind. :smile:
