### ISSUE TITLE
Results Right Aligned

### ISSUE THREAD

**Issue by Silvenga** [CodeConnect/AliveFeedback#48]
As seen below, on large screens having the results right aligned kind of sucks. Am I doing something wrong (or have an incompatible extension installed)?

![2015-10-15_22-00-22](https://cloud.githubusercontent.com/assets/2753330/10532883/7ef1071e-7388-11e5-9f62-43486bdf1c49.png)

VS2015, Alive 0.6.5.1

**Comment by AmadeusW** [comment]
You have the most up to date version of the extension, in which the right alignment is unfortunately  very rudimentary. We will address this issue in the next update. 
I'm sorry for the inconvenience.

**Comment by hatelove** [comment]
In fact, it should be feature from 0.6.3 :laughing: 

Sometimes it bothered me, too. Wish there is appearance setting on Visual Studio. I would like to set the location and font size/color of variable results.

**Comment by JoshVarty** [comment]
It should definitely be more intelligent in where it places the items. I imagine on a high resolution monitor it's even further apart. We'll definitely work on this for the next release.

**Comment by JoshVarty** [comment]
I've fixed this in our internal build and the changes will be contained in our next weekly release. (This Wednesday)

![image](https://i.gyazo.com/b5d0dea16565676bd60dfa9ea4a8948d.gif)

**Comment by JoshVarty** [comment]
It's not a dramatic change on my 13-inch monitor, but it looks like on your screen it'll be ~50% of the distance to the right as it is now.
