### ISSUE TITLE
Support asynchronous tests returning Task

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/AliveFeedback#50]
While working on #49 I noticed that even after all the bugs were fixed and autofiltering was completed that none of the results were showing up inline in the test methods that returned `Task`. I think we need to improve our test runner to ensure it's awaiting the results from these tests. (I assume they're returning immediately)

**Comment by AmadeusW** [comment]
do the test methods have signatures similar to the following?
```
[Fact]
public async Task MyTestMethod()
```

**Comment by JoshVarty** [comment]
Here's a sample:

``` CSharp
[I] public async Task Response() => await this.AssertOnAllResponses(r =>
{
});
```

Where `[I]` is essentially equivalent to `[Fact]` as far as our runner is concerned.
