### ISSUE TITLE
On limitation of Alive to static methods

### ISSUE THREAD

**Issue by AmadeusW** [CodeConnect/AliveFeedback#53]
The following is an exchange between an Alive user and myself about why Alive lets you instrument static methods, but not instance methods:

---

> Curious to understand the static class limitations – can you tell us more about why you need it to be static, rather than newing up an object behind the scenes for inspection purposes?

Static methods are less likely to be stateful compared to instance methods. Looking at example of `Math.Max(a, b)`, this method doesn't need any external information, and it is rightfully static. 
If we allowed users to launch Alive on instance methods directly, we would have hard time instantiating an object. Suppose that the object doesn't have a parameterless constructor. Or suppose that invoking an instance method would be invalid for the new object's state.
Of course, one can write a stateful static method which accesses static fields and properties of a class that haven't been initialized. But we believe that this is a minority of cases.

> I think most of the scenarios where I’d use this would be for prototyping / quick’n’dirty scratch code / educational use – where I’ve probably not bothered to put unit tests together – and static might be an unnecessary limitation. A class with only parameter constructors would surely be handled in a similar way to a method which requires parameters, no?

**Comment by SteveFrench** [comment]
Alive would be much more useful to me to with the restriction on instance methods removed.

**Comment by AmadeusW** [comment]
That's great to hear @SteveFrench. We are currently finishing up work on supporting instance methods!
We hope that this will make Alive more useful and applicable in many more scenarios, particularly in ASP.MVC development.

As the CLR requires us to initialize an instance of a type, in the first release we will support types that have parameterless constructor, or parameters which recursively end up having parameterless constructors. We will elaborate more on this and a workaround when we release, but the long term goals are to make the tool continuously smarter, easier to use, and aware of your codebase.

**Comment by SteveFrench** [comment]
Wonderful!  I am pretty much all asp.net mvc all the time these days - that will be extremely helpful

**Comment by JoshVarty** [comment]
The first iteration of this should be available in our release later today or tomorrow.

Keep in mind that while we can "new up" Controllers in MVC projects, we aren't currently faking actual requests to them. So if you're looking at the `Request` object on a controller, it will be null in Alive.

We're currently investigating a few different ways to overcome this limitation as well.

**Comment by JoshVarty** [comment]
Just pushed out the update. :smile: 

Full changelog at: https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3
