### ISSUE TITLE
Alive button does not show when beginning of the function is not in a visible scope

### ISSUE THREAD

**Issue by jakubbielawa** [CodeConnect/AliveFeedback#56]
The Alive button emerges next to the function name after LMB click on a function's code only when the function name is visible in the editor. I have to click somewhere in the function's code again after scrolling up to see the Alive button.

**Comment by AmadeusW** [comment]
Thank you. I've reproduced the issue and I'll work on a fix

**Comment by AmadeusW** [comment]
@jakubbielawa we've solved this issue in [version 1.0.3](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.0.3). Thank you for your feedback! :stars:
