### ISSUE TITLE
Match the tooltips on result view with the Dark theme

### ISSUE THREAD

**Issue by Phid** [CodeConnect/AliveFeedback#57]
Just a small UI issue.
The tooltips on the right result view (don't know how it's called) are light colour on the VS dark theme, it will be better if it matches the used theme. It jumps too much to the eyes when you hover.

Or maybe would be better to remove them, since the tooltips have the same value already displayed.

**Comment by AmadeusW** [comment]
You're right, the bright on dark was very jarring. It will be fixed in tomorrow's update.
Thank you for your input!

P.S. We won't remove the tooltips as they show the full, untrimmed value, which is the most useful when working with strings and collections

**Comment by Phid** [comment]
Yay! That is really great news! Didn't expect to be that faster. :-)
Regarding the tooltips, I didn't know about that... I just started to play with it; but is good to know it have it's purpose.

Anyway, keep up the amazing work!
I'm looking forward to the update ;-)

**Comment by AmadeusW** [comment]
We matched the background color of all tooltips with the background color of the editor in [version 1.0.3](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.0.3). Thank you for feedback @Phid! :stars:
