### ISSUE TITLE
Crashes VS on Publish

### ISSUE THREAD

**Issue by SteveFrench** [CodeConnect/AliveFeedback#59]
I'm running the current version of Alive - with the newest version of Resharper on VS Enterprise 2015 and whenever I try to publish an asp.net mvc 5 site Visual Studio crashes.  When I disable Alive the problem goes away and everything published normally.  Do you have a debug guide so I can provide more information?

**Comment by AmadeusW** [comment]
Oh no! I'm very sorry for this. Are you using [Visual Studio 2015 update 1](https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx)? Does the problem also happen without Resharper? Does it happen when you build or rebuild the solution, or just publish?

When Visual Studio crashes, it usually meant that Alive didn't handle an exception. We've made sure that no exceptions leak to Visual Studio, but I will double-check all points of contact with VS. Alternatively, something else went wrong - perhaps the compiler went into bad state? It's a resource that Visual Studio and Alive share.

A couple times when my Visual Studio crashed, I noticed that code errors were not underlined and they were not in the error list. Did this ever happen to you, where the errors seem to disappear, and when you build, VS crashes?

**Comment by JoshVarty** [comment]
@SteveFrench When it fails, does anything appear in the Output Window under Alive?

![image](https://i.gyazo.com/c083fd0f520e3eee1d577352391c9dcf.gif)

**Comment by AmadeusW** [comment]
@SteveFrench just wanted to give you an update that I might have reproduced this or a similar issue. 
Visual Studio crashes when
- Alive is enabled
- A solution is externally reloaded (by changing git branch)
- Debugging is started

EDIT: This happens only in certain solutions and is not 100% reproducible

**Comment by SteveFrench** [comment]
I worked it out - the problem was actually the newest version of resharper!  Problem entirely on my end.

**Comment by AmadeusW** [comment]
Sounds good! I'll close this issue, then. Thank you for pointing this one out, as now we know about another bug in Alive.

Let us know if there's anything about Alive that bothers you. We're always trying to improve and it really helps to get honest feedback from our users.
