### ISSUE TITLE
MissingTargetFrameworkException on VS 2013

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/AliveFeedback#60]
From the comments on Visual Studio Gallery:

![image](https://cloud.githubusercontent.com/assets/1249087/11643259/a90077ea-9d10-11e5-9081-d23c6b2acb75.png)

Does this occur when users don't have .NET 4.6 installed? Can we make this error nicer?

**Comment by AmadeusW** [comment]
AFAIK no, we don't have access to the .vsix installer. We can add a note to the **license** which is displayed prior to installation, and we should definitely add a note in the VS extension gallery where users download Alive from.

**Comment by AmadeusW** [comment]
We added a note in the VS extension gallery.

**Comment by JoshVarty** [comment]
I'm going to close this because we can't influence .vsix installation to warn people about this.
