### ISSUE TITLE
Can not handle if(!SomeMethod("String"))

### ISSUE THREAD

**Issue by UlyssesWu** [CodeConnect/AliveFeedback#64]
Yet another strange & _interesting_ bug that I still don't know if it only happens on my computer.

Alive(1.2.0) will show "Syntax Error" when trying to run following code `Test4()`  `Test5()` `Test6()` - which I can't find any syntax error.

After some tests I think it only happens if there are 3 elements in one line: `if` `!` `"` .

Code:

```
    static bool Test1() //PASS, without if
    {
        string test = "Alive_is_great!";
        return !test.Contains("Still");
    }

    static bool Test2() //PASS, without "
    {
        string GLaDOS = "Still";
        string Caroline = "Alive";
        if (!(GLaDOS.Contains(Caroline)))
        {
            return false;
        }
        return true;
    }

    static bool Test3() //PASS, without !
    {
        string test = "Alive_is_great!";
        if (test.Contains("Still"))
        {
            return false;
        }
        return true;
    }
    static bool Test4() //ERROR, with 3 elements together
    {
        string test = "Alive_is_great!";
        if (!test.Contains("Still")) //This line has 3 "Error"
        {
            return true;
        }
        return false;
    }

    static bool Test5() //ERROR
    {
        if (!File.Exists("Alive_Issue.exe"))
        {
            return false;
        }
        return true;
    }

    private static Dictionary<string, bool> _dic = new Dictionary<string, bool>(); 
    static bool Test6() //ERROR
    {
        _dic.Add("test",true); //At first I made a mistake here, now fixed and still error :P
        if (!_dic["test"])
        {
            return false;
        }
        return true;
    }
```

**Comment by AmadeusW** [comment]
Thank you for this detailed error report @UlyssesWu! I'm sorry for this inconvenience. This looks very interesting. I'll get it fixed.

**Comment by AmadeusW** [comment]
We've fixed the issue, expect an update this week. Thanks for your feedback!

**Comment by AmadeusW** [comment]
Fixed in [1.2.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.2.1) :tropical_drink: 

Thank you @UlyssesWu, let me know if there is anything else we can do for you.

**Comment by UlyssesWu** [comment]
Yeah, Test Passed 2/2 ! Thanks & GJ!

...And still a little suggestion:

In `Test5()` , the display for `if (!File.Exists("Alive_Issue.exe"))` is `exe"): False`.

After test, I think the display is always truncated by the last dot (`.`) in string.

**Comment by AmadeusW** [comment]
Oh, I'll fix the issue with the dot. Thank you.
We've been having issues with displaying of negations, and they will be addressed when we re-do the handling of if-statements. The goal is to show which branches are taken and why. The good news is that I recently started writing the code for it, and this feature will come out this month :)

**Comment by UlyssesWu** [comment]
I believe that is the feature we all looking forward to ! :yellow_heart:
