### ISSUE TITLE
Object preview boxes overlap each other

### ISSUE THREAD

**Issue by Ijwu** [CodeConnect/AliveFeedback#68]
When multiple objects are previewed in the same method being run by Alive the boxes produced by those previews simply overlap each other. This contributes to a lot of visual confusion as to what is happening.

As an example, here is an image with a single preview box expanded:

![Single Preview Box](http://puu.sh/mp4Ze/bf803d14d0.png)

Here is an image with two boxes expanded:

![Overlapping Preview Boxes](http://puu.sh/mp52L/03b590c86d.png)

The preview on the higher line simply overlaps the lower line. In my opinion it would be preferable to collapse all other previews in colliding bounds when opening a preview which would otherwise overlap.

An alternative strategy would be to move previews horizontally or vertically to accommodate them all. These options could also both be available and switchable via a settings or configuration menu.

**Comment by AmadeusW** [comment]
Thank you for reporting this issue. This is a case of a bad UI, and I'm not sure what's the best way to address it. Closing other property boxes would be the easiest solution, but there may be some users who want to keep two boxes open for cross-reference.

**Comment by Ijwu** [comment]
That's why I suggested closing only the boxes which would overlap. There is also the option of horizontal positioning, however that depends on how much screen real estate you have to spare.

**Comment by JoshVarty** [comment]
At the very least we need to do a better job of indicating that the boxes are overlapped. Unless you notice the gradient, you might end up thinking it's all one continuous box.

**Comment by AmadeusW** [comment]
We've fixed this in [1.3.3](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3.3) when we addressed a few UI issues with the drilldown boxes. I'm sorry for not closing this issue earlier!
