### ISSUE TITLE
Only recompile a method if there have been no changes to the source within a time period

### ISSUE THREAD

**Issue by Ijwu** [CodeConnect/AliveFeedback#71]
It would be beneficial to only recompile a method if there have been no changes to the code within a certain time limit. This prevent additional work from being done in the background and removes the possibility of VS stuttering as code is written, due to Alive.

A time limit of 150ms-250ms is acceptable. It may take some tinkering to find a nice balance. This is potentially related to: #70 

For the record, Alive _does_ cause VS to stutter depending on what you're doing. To replicate simply start Alive on a static method and hold down your backslash key anywhere in the method.

**Comment by AmadeusW** [comment]
Hi. That's a good idea. In fact, we're already doing it, and the delay is 300ms. See #70 for details.
