### ISSUE TITLE
Alive failing to run code which otherwise compiles correctly.

### ISSUE THREAD

**Issue by Ijwu** [CodeConnect/AliveFeedback#76]
I don't know the cause of this. The code looks fine, syntax-wise, and even compiles properly. Alive seems to be trying to access a namespace like a type or something. I don't really know.

![error](http://puu.sh/mtNvJ/b92a15f0a9.png)

**Comment by Ijwu** [comment]
In every attempt I make to use Alive in this solution it gives the same issue. I receive an error pointing to the line in which the method definition ends. The error message always follows this format: `<Namespace> does not contain a definition for <Sub-Namespace>`. I have not been able to replicate in another solution. I can provide a copy of my code in which it produces the issue. It's all open-source anyway. Let me know if there is anything else I can provide to ease diagnostics.

**Comment by AmadeusW** [comment]
Does this happen in [NyxStudios/Orion](https://github.com/NyxStudios/Orion/) solution?

**Comment by Ijwu** [comment]
Yes, however it did work with a clean clone of the `OTAPI` branch, which is currently where development is focused. I believe something in my changes caused it at some point, I do not know what it was. I can provide the current state of the code if need be.

**Comment by JoshVarty** [comment]
Could you send either Amadeus or I a copy of your repo in its current state? We'll try to take a look this week.

**Comment by Ijwu** [comment]
Grab a copy [here](https://onedrive.live.com/redir?resid=AB18985F47109D0B!64781&authkey=!AJIgD2mK0Ps3dCQ&ithint=file%2c7z).

In an effort to preserve the state of the solution I did not trim it of any misc files so it's going to be a hefty size. Let me know if there are any issues or anything else I can do to help.

**Comment by JoshVarty** [comment]
Thanks, I've pulled it down and will look at it this week. :)

**Comment by JoshVarty** [comment]
Hey sorry to do this, but could you re-share that file with us? (Or the current state of the repo if this is still a problem)

**Comment by Ijwu** [comment]
Woops, sorry! I deleted the file out of OneDrive by mistake. [Here](https://onedrive.live.com/redir?resid=AB18985F47109D0B!64786&authkey=!ABWBsAE109UA1_s&ithint=file%2czip) it is.

I actually don't know if this is still an issue as I haven't had a chance to work on this project in a few weeks and my trial has expired. I've simply grabbed the current state of the project on my machine which is what I assume to be my most current development version.

**Comment by JoshVarty** [comment]
Thanks!

**Comment by JoshVarty** [comment]
Thanks for your help, this was fixed in the 1.3.8 release of Alive. 

The issue was that there was a top level namespace `Orion` as well as a class `Orion` within the same scope. Our generated code wasn't handling this conflict correctly.
