### ISSUE TITLE
Alive takes an extremely long time to startup on projects with many tests.

### ISSUE THREAD

**Issue by JoshVarty** [CodeConnect/AliveFeedback#8]
As we're running all tests on solution load, startup is extremely slow. (And takes up a considerable amount of memory as well).

We should handle this by:
- Intelligently choosing a subset of tests to run instead of running them all.
- Caching test mapping. (what happens when a file is changed on disk?)

**Comment by JoshVarty** [comment]
My 4GB Ultrabook started crying today while running tests on Newtonsoft.Json :(

![image](https://cloud.githubusercontent.com/assets/1249087/7969010/3440dcb6-0a02-11e5-98ef-1aa0a4280454.png)

Definitely a memory leak of some kind.

**Comment by JoshVarty** [comment]
Great news, we've got the

**Comment by JoshVarty** [comment]
Good news, we got it down from 2.4 GB to 300-400MB on my machine. 

It also takes only Alive 15% longer to discover tests and their relationships to invoked methods than it does for VS to run the tests. 

![image](http://i.imgur.com/1dpGVuk.gif)

**Comment by AmadeusW** [comment]
Fixed in 0.2.2. We will be pushing out the update tonight.
