### ISSUE TITLE
Access denied to files

### ISSUE THREAD

**Issue by Suriman** [CodeConnect/AliveFeedback#85]
Alive creates temporary files in AppData \ Local \ Temp and every time I run a test, Alive marks files read-only, thus running the following test throws an exception. I have to manually remove the read-only attribute each time.

**Comment by JoshVarty** [comment]
Are these files auto-generated by Alive or by the tests you're writing? Is there an exception or log present in the Output window (select Alive from the Output window's dropdown to see messages from Alive.)

**Comment by Suriman** [comment]
Files are generated by Alive, I suppose, to run the test. The problem appears in the configuration file. Whenever Alive is executed, the file is marked as read-only and in the next execution of Alive, it appears that change is needed and fails because it is read-only.

![capturealive](https://cloud.githubusercontent.com/assets/3469909/12697526/85c7817e-c786-11e5-97b4-7a3070106705.PNG)

The error appears in the output window:

![capturealive2](https://cloud.githubusercontent.com/assets/3469909/12697682/fa0f4550-c789-11e5-9971-e37af62f3623.PNG)

**Comment by JoshVarty** [comment]
Thanks, we recently made changes to how we emit `.config` files that might've triggered this. We haven't run into it ourselves, but we'll try to fix this ASAP.

**Comment by Suriman** [comment]
Thank you very much!

**Comment by JoshVarty** [comment]
One more quick question, are the `.config` files readonly within your C# project to begin with? I can reproduce the error if I mark mine as readonly, but I want to make sure that's the problem you're running into as well.

**Comment by Suriman** [comment]
Yes, the files in my C# Project are readonly because there are under source control.

**Comment by JoshVarty** [comment]
Alright I've pushed out a new update which should fix this issue you were facing. Thanks for your help, let me know if you have any other issues.

**Comment by Suriman** [comment]
It's OK. Thank you very much!
