### ISSUE TITLE
Errors with generic methods

### ISSUE THREAD

**Issue by Suriman** [CodeConnect/AliveFeedback#86]
Hi,

Errors occur when you try to run tests on a generic method.

![capture4](https://cloud.githubusercontent.com/assets/3469909/12710876/0082b976-c8bb-11e5-831e-9429dcb1645a.PNG)

![capturealive3](https://cloud.githubusercontent.com/assets/3469909/12710880/057a7c98-c8bb-11e5-97d1-5ce8448c5f4a.PNG)

Thank you.

**Comment by JoshVarty** [comment]
Just to double check: That `<T`> you've highlighted is normally colored teal right? (The same color as  `Result`, `DateTime` and `EvaluationMode`? And your code compiler regularly?

I'll take a look at this today.

**Comment by Suriman** [comment]
Hi

<T> is Black color. My code compiles.

Thanks.

**Comment by JoshVarty** [comment]
We've reproduced this, and will be fixing it today. Thanks for you help!

**Comment by Suriman** [comment]
Thank you very much!

**Comment by JoshVarty** [comment]
So we've applied a fix for this in Alive v1.3.5 which I've just released. Let me know if you have any more issues with this.

**Comment by Suriman** [comment]
Hi,

It's OK, but now we have errors with tests that use the Microsoft Fake Framework.

Thanks.

**Comment by JoshVarty** [comment]
Thanks, we've got an issue tracking that feature request at: #83 

I'll look into this over the weekend and try to figure out what kind of investment it will take to support.

**Comment by Suriman** [comment]
OK. Thanks.
