### ISSUE TITLE
Error on initialization 

### ISSUE THREAD

**Issue by ashfaquddin** [CodeConnect/AliveFeedback#89]
I'm having issues running Alive on one of my projects.

[Error, Workspace v1.3.5-vs14.0] There was an error initializing Alive.
[Error, Workspace v1.3.5-vs14.0]  -> Object reference not set to an instance of an object.

**Comment by JoshVarty** [comment]
Does it persist after closing the document? Does it happen on all documents? Is it intermittent or does it happen every time?

**Comment by ashfaquddin** [comment]
it happens only on one production UWP solution. I tried it with other projects and with a new project and its working

**Comment by JoshVarty** [comment]
Interesting, UWP can be a bit of a problem sometimes...

@AmadeusW Have you seen anything similar for UWP projects?

**Comment by AmadeusW** [comment]
My UWP projects work, but we will analyze the stack trace of @ashfaq-uddin's exception and try to find out what's going on.

**Comment by AmadeusW** [comment]
@ashfaq-uddin I have a fix, and I'm wondering if this solves your issues.

You'll need to uninstall Alive from Visual Studio, unzip this file: 
[Alive.1.3.5.vsix.zip](https://github.com/CodeConnect/AliveFeedback/files/127001/Alive.1.3.5.vsix.zip) run the **vsix** and restart Visual Studio.

**Comment by ashfaquddin** [comment]
its working now

**Comment by AmadeusW** [comment]
:tada: We've fixed it in [1.3.7](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3.7), which you can download from VS extension gallery or from Visual Studio. 

Thank you for reporting this issue and we're sorry for the inconvenience!
