### ISSUE TITLE
Cannot Infer Type on Static Generic Methods

### ISSUE THREAD

**Issue by lundmikkel** [CodeConnect/AliveFeedback#93]
Consider a static generic method like this:

``` csharp
public static void Generic<T>(IEnumerable<T>  enumerable) {
    // Fails
}
```

Alive reports an error when calling `Generic()`, saying it is unable to find the type of `T`.

Using a helper method to allow continuation doesn't help:

``` csharp
public static void GenericHelper() {
    Generic<int>(null);
}
```

Or

``` csharp
public static void GenericHelper() {
    Generic(new[] {1, 2, 3, 4});
}
```

The error message looks as follows:
<img width="874" src="https://cloud.githubusercontent.com/assets/1230950/13201672/29c95850-d87c-11e5-9dc4-2bb2ebc2aa16.png">
And:
<img width="876" src="https://cloud.githubusercontent.com/assets/1230950/13202369/a1af1dd4-d898-11e5-8db5-7dcb30428cfb.png">

**Comment by JoshVarty** [comment]
Thanks, this seems like a bug, we'll investigate and try to get a fix out ASAP

**Comment by lundmikkel** [comment]
Great. This even seems to be a problem when trying to run the method using an NUnit test.
The problem seems to be present both in 1.3.8 and 1.3.9.

**Comment by lundmikkel** [comment]
Okay, so this seems not to be a problem related to `null` values, but generic methods. I've updated the original message and title and have provided an extra screenshot.

**Comment by JoshVarty** [comment]
I've reproed this, and have a fix. We'll do some internal testing and review and hopefully push it out tomorrow.

**Comment by lundmikkel** [comment]
When do you expect the fix to be available?

**Comment by JoshVarty** [comment]
I've just pushed this to the VS Gallery. Visual Studio will auto-update or you can force it by downloading the v1.3.10 `.vsix` from: https://visualstudiogallery.msdn.microsoft.com/4af8eb1a-c64f-4da8-9bf0-6835cf3e95c8

**Comment by lundmikkel** [comment]
Great. It seems to be working again. Thanks a lot.

**Comment by JoshVarty** [comment]
:+1: Thanks for your help :)
