### ISSUE TITLE
Can Alive support getter/setter property?

### ISSUE THREAD

**Issue by wellwind** [CodeConnect/AliveFeedback#99]
Currently Alive works fine in methods in class, but sometimes I write code in getter/setter like

``` csharp
        public string NextOrder
        {
            get
            {
                if (Order.Equals("asc", StringComparison.OrdinalIgnoreCase))
                {
                    return "desc";
                }

                if (Order.Equals("desc", StringComparison.OrdinalIgnoreCase))
                {
                    return string.Empty;
                }

                return "asc";
            }
        }
```

Then Alive didn't work.

**Comment by AmadeusW** [comment]
This is something we've considered exploring.
It would require changes to the user interface that invokes methods (and in the future, properties) and changes to the way Alive internally interacts with the code. 

We can't guarantee when we will do it, but future changes to the user interface would yield themselves practical for this use case. What do you think @JoshVarty?

**Comment by lundmikkel** [comment]
@wellwind Off topic, but it seems you should rather use an enum for that ;)
